### PR TITLE
Support HTML-comments

### PR DESCRIPTION
**Pull request by erik-sjoestedt**
We need to preserve HTML-comments, for IE-fixes :)

Does this look alright?

### CODE REVIEW

**Comment by Neppord** [comment]
@erik-sjoestedt could you add a test case with a ie fix comment, to show if and why it should be used :)!

**Comment by erik-sjoestedt** [comment]
@Neppord Fixed some more tests

**Comment by erik-sjoestedt** [comment]
@Neppord I tested this on the site that uses Rheo, and it's working!

**Comment by Neppord** [comment]
@erik-sjoestedt your changes are in and published to npm.

**Pull request closed without merging**
